# Generated by Django 2.2 on 2020-01-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('availability', models.CharField(choices=[('In Stock', 'in-stock'), ('Out Of Stock', 'out-of-stock')], max_length=20)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
