# Generated by Django 2.2 on 2020-01-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='availability',
            field=models.CharField(choices=[('In Stock', 'in-stock'), ('Out Of Stock', 'out-of-stock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
