# Generated by Django 2.2 on 2020-01-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20200110_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='imageUrl',
        ),
    ]
